version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        command: echo "Building complete"
  test-node:
    docker:
    - image: circleci/node
    steps:
    - run:
        command: echo "Testing complete"
  test-node-8:
    docker:
    - image: circleci/node:8
    steps:
    - run:
        command: echo "Testing complete"
  test-node-6:
    docker:
    - image: circleci/node:6
    steps:
    - run:
        command: echo "Testing complete"
  deploy:
    docker:
    - image: circleci/node
    steps:
    - run:
        command: echo "DEPLOYING"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build
    - test-node
    - test-node-8
    - test-node-6
    - deploy:
        requires:
        - test-node
        - test-node-8
        - test-node-6