version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        command: echo "Building complete"
  test:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        command: echo "Testing complete"
  deploy:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        command: echo "Deploy complete"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
    - deploy:
        filters:
          tags:
            only: /^beta.*/
          branches:
            ignore: /.*/
        requires:
        - test